FROM mcr.microsoft.com/devcontainers/base:ubuntu

# install homebrew
RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install npm 
RUN brew install node